In [1]:
import pandas as pd
import numpy as np
import datetime

In [2]:
tempA = pd.read_csv('training.tsv', sep='\t', names = ['id', 'date', 'action'])

# checking to see which dates are the first for each user
tempA.drop_duplicates(subset = 'id', inplace = True)
tempA = tempA.rename(columns = {'date':'first_date'})
# Reformatting data types
tempA['first_date'] = pd.to_datetime(tempA['first_date'])

tempB = pd.read_csv('training.tsv', sep='\t', names = ['id', 'date', 'action'])

# adding the last action dates to the features list
tempB.drop_duplicates(subset = 'id', keep = 'last', inplace = True)
tempB = tempB.rename(columns = {'date':'last_date'})
# Reformatting data types
tempB['last_date'] = pd.to_datetime(tempB['last_date'])

temp4 = tempA.merge(tempB, on = 'id')
temp4['days_as_user'] = temp4.last_date - temp4.first_date
temp4 = temp4.loc[:, ['id', 'days_as_user']]

temp4['days_as_user'] = (temp4['days_as_user']/ np.timedelta64(1, 'D')).astype(int)

temp4

                     id  days_as_user
0       0000ecf58c94668            70
1       000132f21724ee2             0
2       0001b315b991cf0            55
3       000269150971d08            51
4       000297ba4fa5026            54
5       000342505b41079            84
6       0003b304dd7cfae             0
7       0003ee709c3b5dc            42
8       00049247bdf8ddf            54
9       0004cf13b5e07dd             0
10      000711b04f50795            84
11      00071be52946ef6            66
12      00074a7bf0072e1            13
13      000774de3db21c8            70
14      0007ed3552f1d91            28
15      000839a75b6a63b            28
16      0008f1827dd6a01             0
17      000942b81a09db8             6
18      000954284fb33ac            54
19      000983e8b71491b            52
20      0009f400b5ab803            38
21      000a1ffea4566ee            82
22      000a8b5f5af6a03             0
23      000b88b58badfbb            10
24      000b9c48c0e39d5            21
25      000bbf1604c8652             8
26      000bc16d10339e0             0
27      000bc6834332f42            82
28      000c4df369cdbb9             0
29      000d34fc618b2b2             0
...                 ...           ...
132780  fff2f3ee8045eec            70
132781  fff313762aebe2e            30
132782  fff34619f90352b            83
132783  fff37ffb184013c             0
132784  fff3f22249d0368            30
132785  fff590710b97ae4             0
132786  fff5ed08f099429            61
132787  fff64729b026af4             0
132788  fff647e6ede1254            34
132789  fff64a7c709fb81             0
132790  fff65fd4ed06edd             2
132791  fff67b9a6117b36             0
132792  fff7653a49d7005             0
132793  fff7820ed2889ee             0
132794  fff85aed507b775            26
132795  fff875fdfa950d0            15
132796  fff8af805b4c377             0
132797  fff8bbc43270b6e             0
132798  fff975dc412bdbf            78
132799  fff9854326214a5             1
132800  fffa171cf71aa65            21
132801  fffa2a4404d591e             0
132802  fffa58bf7ea0a59            83
132803  fffad910ea21fdf            21
132804  fffbc70a141287a             0
132805  fffc7f2ad169c6b             0
132806  fffd77a0266d37c            35
132807  fffed482b52afd8             0
132808  ffffa4cc0190881             0
132809  ffffecdd8dc6174            36

[132810 rows x 2 columns]

In [3]:
temp4.to_csv('temp4.csv')